server:
  port: 8081
keycloak:
  url: http://localhost:8080/realms/Tech
  client-id: external-client
  client-secret: secret

spring:
  application:
    name: InsuranceApi
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Tech